
# confige datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/hospital?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=141248690405Zt.

# confige JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


#security
# app.jwt.secret=ngayanhmatemcathegioinayphaichiudaukhothanglayemdisephaitragia
# app.jwt.access-expires-in-mili-seconds=900000